databases:
  - name: ar10_tracker_db
    plan: free
    databaseName: ar10_tracker_db
    user: ar10_user

services:
  - type: web
    plan: free
    name: ar10_tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ar10_tracker.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ar10_tracker_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
