# Generated by Django 4.1.6 on 2023-02-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "number_shots",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of shots completed"
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "target_distance",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                (
                    "f_coefficient",
                    models.PositiveSmallIntegerField(
                        verbose_name="Ballistic 'F' coefficient"
                    ),
                ),
                (
                    "aiming_time",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="T"
                    ),
                ),
                (
                    "score_decimal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="R"
                    ),
                ),
                ("ten_zero", models.PositiveSmallIntegerField(verbose_name="10.0")),
                ("ten_azero", models.PositiveSmallIntegerField(verbose_name="10a0")),
                ("ten_five", models.PositiveSmallIntegerField(verbose_name="10.5")),
                ("ten_afive", models.PositiveSmallIntegerField(verbose_name="10a5")),
                (
                    "s1",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="S1"
                    ),
                ),
                (
                    "s2",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="S2"
                    ),
                ),
                (
                    "da",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="DA"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "training data",
                "ordering": ["date_time"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competition_name", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField()),
                ("match_number", models.PositiveSmallIntegerField()),
                ("qual_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "competition data",
                "ordering": ["date_time"],
            },
        ),
    ]
