# Generated by Django 4.1.6 on 2023-03-02 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0002_trainingdata_competitiondata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competitiondata",
            options={"ordering": ["date"], "verbose_name_plural": "competition data"},
        ),
        migrations.AlterModelOptions(
            name="trainingdata",
            options={"ordering": ["date"], "verbose_name_plural": "training data"},
        ),
        migrations.RemoveField(
            model_name="competitiondata",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="trainingdata",
            name="date_time",
        ),
        migrations.AddField(
            model_name="competitiondata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
