# Generated by Django 4.1.6 on 2023-03-08 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0003_alter_competitiondata_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingdata",
            name="score_decimal",
        ),
    ]
