# Generated by Django 4.1.6 on 2023-03-17 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0004_remove_trainingdata_score_decimal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competitiondata",
            options={"ordering": ["-date"], "verbose_name_plural": "competition data"},
        ),
        migrations.AlterModelOptions(
            name="trainingdata",
            options={"ordering": ["-date"], "verbose_name_plural": "training data"},
        ),
    ]
